### ISSUE TITLE
error

### ISSUE THREAD

**Issue by anjaney-ai** [anjaneyshrivastava/finetune_llama2#1]
{
	"name": "NotImplementedError",
	"message": "Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device.",
	"stack": "---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[15], line 1
----> 1 trainer=SFTTrainer(
      2     model=model,
      3     train_dataset=dataset_name,
      4     peft_config=peft_config,
      5     dataset_text_field=\"text\",
      6     max_seq_length=max_seq_length,
      7     tokenizer=tokenizer,
      8     args=training_arguments,
      9     packing=packing,
     10 )

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\huggingface_hub\\utils\\_deprecation.py:101, in _deprecate_arguments.<locals>._inner_deprecate_positional_args.<locals>.inner_f(*args, **kwargs)
     99         message += \"\
\
\" + custom_message
    100     warnings.warn(message, FutureWarning)
--> 101 return f(*args, **kwargs)

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\trl\\trainer\\sft_trainer.py:413, in SFTTrainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics, peft_config, dataset_text_field, packing, formatting_func, max_seq_length, infinite, num_of_sequences, chars_per_token, dataset_num_proc, dataset_batch_size, neftune_noise_alpha, model_init_kwargs, dataset_kwargs, eval_packing)
    407 if tokenizer.padding_side is not None and tokenizer.padding_side != \"right\":
    408     warnings.warn(
    409         \"You passed a tokenizer with `padding_side` not equal to `right` to the SFTTrainer. This might lead to some unexpected behaviour due to \"
    410         \"overflow issues when training a model in half-precision. You might consider adding `tokenizer.padding_side = 'right'` to your code.\"
    411     )
--> 413 super().__init__(
    414     model=model,
    415     args=args,
    416     data_collator=data_collator,
    417     train_dataset=train_dataset,
    418     eval_dataset=eval_dataset,
    419     tokenizer=tokenizer,
    420     model_init=model_init,
    421     compute_metrics=compute_metrics,
    422     callbacks=callbacks,
    423     optimizers=optimizers,
    424     preprocess_logits_for_metrics=preprocess_logits_for_metrics,
    425 )
    427 # Add tags for models that have been loaded with the correct transformers version
    428 if hasattr(self.model, \"add_model_tags\"):

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\transformers\\trainer.py:535, in Trainer.__init__(self, model, args, data_collator, train_dataset, eval_dataset, tokenizer, model_init, compute_metrics, callbacks, optimizers, preprocess_logits_for_metrics)
    530 # Bnb Quantized models doesn't support `.to` operation.
    531 if (
    532     self.place_model_on_device
    533     and not getattr(model, \"quantization_method\", None) == QuantizationMethod.BITS_AND_BYTES
    534 ):
--> 535     self._move_model_to_device(model, args.device)
    537 # Force n_gpu to 1 to avoid DataParallel as MP will manage the GPUs
    538 if self.is_model_parallel:

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\transformers\\trainer.py:782, in Trainer._move_model_to_device(self, model, device)
    781 def _move_model_to_device(self, model, device):
--> 782     model = model.to(device)
    783     # Moving a model to an XLA device disconnects the tied weights, so we have to retie them.
    784     if self.args.parallel_mode == ParallelMode.TPU and hasattr(model, \"tie_weights\"):

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:1174, in Module.to(self, *args, **kwargs)
   1171         else:
   1172             raise
-> 1174 return self._apply(convert)

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:780, in Module._apply(self, fn, recurse)
    778 if recurse:
    779     for module in self.children():
--> 780         module._apply(fn)
    782 def compute_should_use_set_data(tensor, tensor_applied):
    783     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    784         # If the new tensor has compatible tensor type as the existing tensor,
    785         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    790         # global flag to let the user control whether they want the future
    791         # behavior of overwriting the existing tensor or not.

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:780, in Module._apply(self, fn, recurse)
    778 if recurse:
    779     for module in self.children():
--> 780         module._apply(fn)
    782 def compute_should_use_set_data(tensor, tensor_applied):
    783     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    784         # If the new tensor has compatible tensor type as the existing tensor,
    785         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    790         # global flag to let the user control whether they want the future
    791         # behavior of overwriting the existing tensor or not.

    [... skipping similar frames: Module._apply at line 780 (5 times)]

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:780, in Module._apply(self, fn, recurse)
    778 if recurse:
    779     for module in self.children():
--> 780         module._apply(fn)
    782 def compute_should_use_set_data(tensor, tensor_applied):
    783     if torch._has_compatible_shallow_copy_type(tensor, tensor_applied):
    784         # If the new tensor has compatible tensor type as the existing tensor,
    785         # the current behavior is to change the tensor in-place using `.data =`,
   (...)
    790         # global flag to let the user control whether they want the future
    791         # behavior of overwriting the existing tensor or not.

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:805, in Module._apply(self, fn, recurse)
    801 # Tensors stored in modules are graph leaves, and we don't want to
    802 # track autograd history of `param_applied`, so we have to use
    803 # `with torch.no_grad():`
    804 with torch.no_grad():
--> 805     param_applied = fn(param)
    806 p_should_use_set_data = compute_should_use_set_data(param, param_applied)
    808 # subclasses may have multiple child tensors so we need to use swap_tensors

File d:\\anjaney.shrivastava\\OneDrive - Infosys Limited\\Project\\heirarchial_json\\pdf_json_env\\Lib\\site-packages\\torch\
n\\modules\\module.py:1167, in Module.to.<locals>.convert(t)
   1165 except NotImplementedError as e:
   1166     if str(e) == \"Cannot copy out of meta tensor; no data!\":
-> 1167         raise NotImplementedError(
   1168             f\"{e} Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() \"
   1169             f\"when moving module from meta to a different device.\"
   1170         ) from None
   1171     else:
   1172         raise

NotImplementedError: Cannot copy out of meta tensor; no data! Please use torch.nn.Module.to_empty() instead of torch.nn.Module.to() when moving module from meta to a different device."
}

**Comment by anjaneyshrivastava** [comment]
import os
import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
)
from peft import LoraConfig
from trl import SFTTrainer

# The path to your local model directory
local_model_dir = "/path_to_your_model_directory/"

# Fine-tuned model name
new_model = "Llama-2-7b-chat-finetune"

################################################################################
# LoRA parameters (if applicable for your CPU training setup)
################################################################################

# LoRA attention dimension
lora_r = 64

# Alpha parameter for LoRA scaling
lora_alpha = 16

# Dropout probability for LoRA layers
lora_dropout = 0.1

################################################################################
# TrainingArguments parameters
################################################################################

# Output directory where the model predictions and checkpoints will be stored
output_dir = "./results"

# Number of training epochs
num_train_epochs = 1

# Enable fp16/bf16 training (set bf16 to True with an A100)
fp16 = False
bf16 = False

# Batch size per device for training (adjust for CPU)
per_device_train_batch_size = 1

# Batch size per device for evaluation (adjust for CPU)
per_device_eval_batch_size = 1

# Number of update steps to accumulate the gradients for
gradient_accumulation_steps = 1

# Enable gradient checkpointing
gradient_checkpointing = False

# Maximum gradient norm (gradient clipping)
max_grad_norm = 0.3

# Initial learning rate (AdamW optimizer)
learning_rate = 2e-4

# Weight decay to apply to all layers except bias/LayerNorm weights
weight_decay = 0.001

# Optimizer to use
optim = "adamw"

# Learning rate schedule
lr_scheduler_type = "cosine"

# Number of training steps (overrides num_train_epochs)
max_steps = -1

# Ratio of steps for a linear warmup (from 0 to learning rate)
warmup_ratio = 0.03

# Group sequences into batches with the same length
group_by_length = True

# Save checkpoint every X updates steps
save_steps = 0

# Log every X updates steps
logging_steps = 25

################################################################################
# SFT parameters
################################################################################

# Maximum sequence length to use
max_seq_length = None

# Pack multiple short examples in the same input sequence to increase efficiency
packing = False

# Load your custom dataset
custom_dataset_path = 'path_to_your/formatted_dataset.txt'
dataset = Dataset.from_dict({"text": open(custom_dataset_path, "r", encoding="utf-8").readlines()})

# Load tokenizer and model from the local directory
tokenizer = AutoTokenizer.from_pretrained(local_model_dir)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Load the base model from the local directory with to_empty workaround
model = AutoModelForCausalLM.from_pretrained(local_model_dir, torch_dtype=torch.float32)
model = model.to_empty(device=torch.device("cpu"))
model = model.to(torch.device("cpu"))
model.config.use_cache = False

# Load LoRA configuration (only if you're using LoRA)
peft_config = LoraConfig(
    lora_alpha=lora_alpha,
    lora_dropout=lora_dropout,
    r=lora_r,
    bias="none",
    task_type="CAUSAL_LM",
)

# Set training parameters
training_arguments = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=num_train_epochs,
    per_device_train_batch_size=per_device_train_batch_size,
    gradient_accumulation_steps=gradient_accumulation_steps,
    optim=optim,
    save_steps=save_steps,
    logging_steps=logging_steps,
    learning_rate=learning_rate,
    weight_decay=weight_decay,
    fp16=fp16,
    bf16=bf16,
    max_grad_norm=max_grad_norm,
    max_steps=max_steps,
    warmup_ratio=warmup_ratio,
    group_by_length=group_by_length,
    lr_scheduler_type=lr_scheduler_type,
    report_to="tensorboard"
)

# Set supervised fine-tuning parameters
trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length=max_seq_length,
    tokenizer=tokenizer,
    args=training_arguments,
    packing=packing,
)

# Train the model
trainer.train()
